name: pr-actions
on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check linter
        run: npm run lint
